language: elixir

elixir:
  - 1.15

otp_release:
  - 25.1

matrix:
  exclude:
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 21.3

before_script:
  - mix deps.get

script:
  - mix lint.all
  - mix test